ExperiencesData = [
	{
		num : 1,
		x : 0,
		y : 0,
		z: 0,
		songPlaying : true,
		userClose : false,
		video : "https://evejweinberg.github.io/videos/1.mp4",
		voice : "https://evejweinberg.github.io/anxeity/01_01.wav",
		firstSfx : "https://evejweinberg.github.io/anxeity/01_02.wav",
		secondSfx : "https://evejweinberg.github.io/anxeity/01_03.wav",
		
	},
	{
		num : 2,
		x : 0,
		y : 0,
		z: 0,
		songPlaying : true,
		userClose : false,
		video : "https://evejweinberg.github.io/videos/2.mp4",
		voice : "https://evejweinberg.github.io/anxeity/02_01.wav",
		firstSfx : "https://evejweinberg.github.io/anxeity/02_02.wav",
		secondSfx : "https://evejweinberg.github.io/anxeity/02_03.wav",
	},
	{
		num : 3,
		x : 0,
		y : 0,
		z: 0,
		songPlaying : true,
		userClose : false,
		video : "https://evejweinberg.github.io/videos/3.mp4",
		voice : "https://evejweinberg.github.io/anxeity/03_01.wav",
		firstSfx : "https://evejweinberg.github.io/anxeity/03_02.wav",
		secondSfx : "https://evejweinberg.github.io/anxeity/03_03.wav",
	},
	{
		num : 4,
		x : 0,
		y : 0,
		z: 0,
		songPlaying : true,
		userClose : false,
		video : "https://evejweinberg.github.io/videos/4.mp4",
		voice : "https://evejweinberg.github.io/anxeity/04_01.wav",
		firstSfx : "https://evejweinberg.github.io/anxeity/04_02.wav",
		secondSfx : "https://evejweinberg.github.io/anxeity/04_03.wav",
	},
	{
		num : 5,
		x : 0,
		y : 0,
		z: 0,
		songPlaying : true,
		userClose : false,
		video : "https://evejweinberg.github.io/videos/5.mp4",
		voice : "https://evejweinberg.github.io/anxeity/05_01.wav",
		firstSfx : "https://evejweinberg.github.io/anxeity/05_02.wav",
		secondSfx : "https://evejweinberg.github.io/anxeity/05_03.wav",
	},
	{
		num : 6,
		x : 0,
		y : 0,
		z: 0,
		songPlaying : true,
		userClose : false,
		video : "https://evejweinberg.github.io/videos/6.mp4",
		voice : "https://evejweinberg.github.io/anxeity/06_01.wav",
		firstSfx : "https://evejweinberg.github.io/anxeity/06_02.wav",
		secondSfx : "https://evejweinberg.github.io/anxeity/06_03.wav",
	}]