ExperiencesData = [
	{
		num : 1,
		x : 0,
		y : 0,
		z: 0,
		songPlaying : true,
		userClose : false,
		video : "https://evejweinberg.github.io/videos/1.mp4",
		voice : "https://evejweinberg.github.io/samples/1.wav",
		
	},
	{
		num : 2,
		x : 0,
		y : 0,
		z: 0,
		songPlaying : true,
		userClose : false,
		video : "https://evejweinberg.github.io/videos/2.mp4",
		voice : "https://evejweinberg.github.io/samples/2.wav",
	},
	{
		num : 3,
		x : 0,
		y : 0,
		z: 0,
		songPlaying : true,
		userClose : false,
		video : "https://evejweinberg.github.io/videos/3.mp4",
		voice : "https://evejweinberg.github.io/samples/3.wav",
	},
	{
		num : 4,
		x : 0,
		y : 0,
		z: 0,
		songPlaying : true,
		userClose : false,
		video : "https://evejweinberg.github.io/videos/4.mp4",
		voice : "https://evejweinberg.github.io/samples/4.wav",
	},
	{
		num : 5,
		x : 0,
		y : 0,
		z: 0,
		songPlaying : true,
		userClose : false,
		video : "https://evejweinberg.github.io/videos/5.mp4",
		voice : "https://evejweinberg.github.io/samples/5.wav",
	},
	{
		num : 6,
		x : 0,
		y : 0,
		z: 0,
		songPlaying : true,
		userClose : false,
		video : "https://evejweinberg.github.io/videos/6.mp4",
		voice : "https://evejweinberg.github.io/samples/6.wav",
	}]